# Generated by Django 3.2.3 on 2021-05-31 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plan',
            name='save',
        ),
        migrations.AddField(
            model_name='plan',
            name='save_money',
            field=models.FloatField(blank=True, default=0, verbose_name='Dinheiro desejável a poupar (mensais)'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='plan',
            name='earn',
            field=models.FloatField(blank=True, verbose_name='Ganhos (mensais)'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='fixed',
            field=models.FloatField(blank=True, verbose_name='Gastos totais (mensais)'),
        ),
    ]
