# Generated by Django 3.2.3 on 2021-05-31 19:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0003_expense'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='value',
            field=models.FloatField(blank=True, default=0, verbose_name='Valor'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='expense',
            name='user',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
